### PR TITLE
GNU/Hurd support, closes #40

### LINKED ISSUE #40: Debian GNU/Hurd support?
I've installed the latest Debian GNU/Hurd using [this guide](https://www.debian.org/ports/hurd/hurd-install). And I'm trying to get pfetch to run. It says `GNU is not currently supported` though. I know it's running `coreutils` but I'm not sure if it POSIX compatible or something.

### PR DESCRIPTION
**Pull request by ghost**
image

### CODE REVIEW

**Comment by Un1q32** [comment]
Did you delete the repo on accident?

**Comment by Un1q32** [comment]
Sorry I thought this was in my repo, didnt read the notification fully

**Comment by Un1q32** [comment]
I'm merging this into my fork at https://github.com/Un1q32/pfetch, I would have you as a co-author but I would need an email and all your activity is private so I can't get one

**Comment by ghost** [comment]
@Un1q32 you are free to author the commit yourself. I do not intend to use this github account or the original commit username and email any longer.

**Pull request closed without merging**
